version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      RAILS_ENV: development

    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:prepare &&
        bundle exec rails s -b 0.0.0.0
      "
